version: '3.6'

services:
  inductor-pg:
    image: postgres:14-alpine
    hostname: inductor-pg
    container_name: inductor-pg
    ports:
      - 9999:5432
    environment:
      POSTGRES_PASSWORD: inductor
      POSTGRES_USER: inductor
      POSTGRES_DB: inductor
    mem_limit: 200m