export enum MySQLColumnType {
  CHAR = 'char',
  VARCHAR = 'varchar',
  BINARY = 'binary',
  VARBINARY = 'varbinary',
  TINYBLOB = 'tinyblob',
  TINYTEXT = 'tinytext',
  TEXT = 'text',
  BLOB = 'blob',
  MEDIUMTEXT = 'mediumtext',
  MEDIUMBLOB = 'mediumblob',
  LONGTEXT = 'longtext',
  LONGBLOB = 'longblob',
  ENUM = 'enum',
  SET = 'set',

  BIT = 'bit',
  TINYINT = 'tinyint',
  BOOL = 'bool',
  SMALLINT = 'smallint',
  MEDIUMINT = 'mediumint',
  INTEGER = 'integer',
  BIGINT = 'bigint',
  FLOAT = 'float',
  DOUBLE = 'double',
  DECIMAL = 'decimal',

  DATE = 'date',
  DATETIME = 'datetime',
  TIMESTAMP = 'timestamp',
  TIME = 'time',
  YEAR = 'year',
}
